---
- name: restart promtail
  become: true
  systemd:
    daemon_reload: true
    name: promtail
    state: restarted

- name: reload promtail
  become: true
  systemd:
    name: promtail
    state: reloaded